---
- name: Install python packages
  pip:
    name: influxdb

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "/opt/influxdb/data"
    - "/opt/influxdb/config"

# NOTE: If you want to recreate database, delete /opt/influxdb directory manually or otherwise DB init won't happen at container start

- name: Start influxdb container
  docker_container:
    name: influxdb_database
    image: "{{ influxdb_image }}"
    command: "influxd run"
    restart_policy: always
    volumes:
      - "/opt/influxdb/data:/var/lib/influxdb"
#      - "/opt/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    ports:
      - "{{ influxdb_tcp_port }}:{{ influxdb_tcp_port }}"
    env:
      INFLUXDB_HTTP_AUTH_ENABLED: true
      INFLUXDB_ADMIN_USER: "{{ influxdb_admin_username }}"
      INFLUXDB_ADMIN_PASSWORD: "{{ influxdb_admin_password }}"
      INFLUXDB_DB: "{{ influx_db_name }}"
      INFLUXDB_USER: "{{ influxdb_raspi_username }}"
      INFLUXDB_USER_PASSWORD: "{{ influxdb_raspi_password }}"
  register: start_result


