---
- block:
  - name: Install EPEL repository
    yum:
      name: epel-release

  - name: Install packages
    yum:
      name:
       - python-pip
       - libselinux-python

  # Disabling SELinux makes it faster to install other stuff as with SELinux enabled
  # semodule process is using lots of CPU time
  - name: Disable SELinux permanently
    selinux:
      state: disabled

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- block:
  # This often fails after VM creation, therefore doing retries
  - name: Install python setuptools
    package:
      name: python-setuptools
    register: result
    until: result is succeeded
    retries: 10
    delay: 5

  - name: Install pip
    easy_install:
      name: pip
      state: latest

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# docker-py is needed for managing containers with Ansible
- name: Install docker-py
  pip:
    name: docker-py
    state: latest

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

# Docker and firewalld mess in CentOS 7, so let's disable it.
# https://sanenthusiast.com/docker-and-firewalld-mess-in-centos-7/
# Bug report: https://github.com/docker/docker/issues/16137
- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  register: result
  failed_when: result is failed and not 'Could not find the requested service' in result.msg
